version: "3.8"
services:
  labs_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'labs_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: